group = me.biquaternions.fish
version = 1.21.11-R0.1-SNAPSHOT

mcVersion = 1.21.11
apiVersion = 1.21.11

pufferfishCommit = 62a5fc3f44f6853597e91ae57de556f4ebc2a872
updatingMinecraft = false

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
