group = me.biquaternions.fish
version = 1.21.11-R0.1-SNAPSHOT

mcVersion = 1.21.11
apiVersion = 1.21.11

pufferfishCommit = 47b1ea0a020d6f23b4613c6d11c8177f28aec431
updatingMinecraft = false

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
