group = me.biquaternions.fish
version = 1.21.11-R0.1-SNAPSHOT

mcVersion = 1.21.11
apiVersion = 1.21.11

pufferfishCommit = c628b85f6cd9c6bca525ca8fc6920c98834e7081
updatingMinecraft = false

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
